contd... voting.ipynb 

here we will do regression problem/data prev we worked with classificaiton 



In [19]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import VotingRegressor
from sklearn.metrics import r2_score

In [1]:
from sklearn.datasets import load_diabetes

data = load_diabetes()

X = data.data
y = data.target

In [2]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]], shape=(442, 10))

In [3]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [26]:
lr=LinearRegression()
svm=SVR() #support vector
dt=DecisionTreeRegressor()

estimators=[('lreg',lr),('svm',svm),('tree',dt)]

# first lets do corssval 


for estimator in estimators:
  scores = cross_val_score(estimator[1],X=X_train,y=y_train,scoring='r2',cv=2)
  print(estimator[0],np.round(np.mean(scores),2))

lreg 0.43
svm 0.02
tree 0.06


In [29]:
# very low scores now lests trying voting ensemble 


voting_ensemble_regression=VotingRegressor(estimators=estimators)
voting_ensemble_regression.fit(X_train,y_train)
ypred=voting_ensemble_regression.predict(X_test)
ypred

array([159.1409481 , 183.87775198, 117.00169957, 246.28465984,
       103.52114576, 151.76061019, 217.73675594, 188.13967679,
       168.0113859 , 146.22247226, 112.19561591, 153.31355422,
       111.00441013, 210.21472742,  82.32313593, 111.28256672,
       181.78972955, 227.80454234, 196.15446108, 168.70537124,
       142.95537582, 115.02757523,  79.50591676, 163.67270719,
       144.87552542, 169.54434085, 212.19638783, 136.56762451,
        76.97144086, 139.53018275, 149.47021981,  90.47793776,
       152.49911717, 153.77099684, 154.35791831, 174.26474228,
       114.91398418, 114.16936666, 192.25369339,  85.50864364,
        77.13138101, 119.52277804, 187.21679663, 188.71604722,
       148.64488727,  88.66068334,  77.08289339, 130.67668236,
        72.37864119, 162.38943942, 115.708726  ,  90.3314767 ,
       130.57855731,  96.45774693, 205.90904301, 147.32760624,
       107.61632486, 218.31153325,  99.13580731,  83.70146422,
       153.95436763, 166.11925169, 138.45443205, 137.97

In [30]:
r2_score(y_test,ypred)

0.3767525725121649

In [32]:
vr = VotingRegressor(estimators)
scores = cross_val_score(vr,X,y,scoring='r2',cv=10)
print("Voting Regressor",np.round(np.mean(scores),2))

Voting Regressor 0.35
